name: Deploy Site on push
on:
  push:
    branches: [ master, Development ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run production
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
       sftp: true # optional
       host: ${{ secrets.brooks.dreamhost.com }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
       port: 21 # optional, default is: 21
       username: ${{ secrets.dh_ycrkg7 }} # FTP username
       password: ${{ secrets.eW401zFU }} # FTP password
       remote_folder: ${{ secrets.oakarboleda.com }} # optional, remote path of your FTP server
       local_folder: dist # optional, local path, default is: dist
       cleanup: false # optional, remove existing files inside FTP remote folder
       include: [] # optional, e.g. ['dist']
       exclude: ['node_modules/**', '.git/**', '*.env']
       pasive: true # optional
